import type { Station } from './types';

export const STATIONS: Station[] = [
  {
    id: 'posto-natureza-1',
    name: 'Posto Natureza 1',
    competitors: [
      { id: 'concorrente-1-1', name: 'Concorrente 1' },
      { id: 'concorrente-1-2', name: 'Concorrente 2' },
      { id: 'concorrente-1-3', name: 'Concorrente 3' },
      { id: 'concorrente-1-4', name: 'Concorrente 4' },
      { id: 'concorrente-1-5', name: 'Concorrente 5' },
      { id: 'concorrente-1-6', name: 'Concorrente 6' },
      { id: 'concorrente-1-7', name: 'Concorrente 7' },
      { id: 'concorrente-1-8', name: 'Concorrente 8' },
      { id: 'concorrente-1-9', name: 'Concorrente 9' },
      { id: 'concorrente-1-10', name: 'Concorrente 10' },
    ],
  },
  {
    id: 'posto-natureza-2',
    name: 'Posto Natureza 2',
    competitors: [
        { id: 'concorrente-2-1', name: 'Concorrente A' },
        { id: 'concorrente-2-2', name: 'Concorrente B' },
        { id: 'concorrente-2-3', name: 'Concorrente C' },
        { id: 'concorrente-2-4', name: 'Concorrente D' },
        { id: 'concorrente-2-5', name: 'Concorrente E' },
        { id: 'concorrente-2-6', name: 'Concorrente F' },
        { id: 'concorrente-2-7', name: 'Concorrente G' },
        { id: 'concorrente-2-8', name: 'Concorrente H' },
        { id: 'concorrente-2-9', name: 'Concorrente I' },
        { id: 'concorrente-2-10', name: 'Concorrente J' },
    ],
  },
  {
    id: 'posto-natureza-3',
    name: 'Posto Natureza 3',
    competitors: [
        { id: 'concorrente-3-1', name: 'Competidor Alpha' },
        { id: 'concorrente-3-2', name: 'Competidor Beta' },
        { id: 'concorrente-3-3', name: 'Competidor Gamma' },
        { id: 'concorrente-3-4', name: 'Competidor Delta' },
        { id: 'concorrente-3-5', name: 'Competidor Epsilon' },
        { id: 'concorrente-3-6', name: 'Competidor Zeta' },
        { id: 'concorrente-3-7', name: 'Competidor Eta' },
        { id: 'concorrente-3-8', name: 'Competidor Theta' },
        { id: 'concorrente-3-9', name: 'Competidor Iota' },
        { id: 'concorrente-3-10', name: 'Competidor Kappa' },
    ],
  },
  {
    id: 'posto-natureza-4',
    name: 'Posto Natureza 4',
    competitors: [
        { id: 'concorrente-4-1', name: 'Posto Sol' },
        { id: 'concorrente-4-2', name: 'Posto Lua' },
        { id: 'concorrente-4-3', name: 'Posto Estrela' },
        { id: 'concorrente-4-4', name: 'Posto Cometa' },
        { id: 'concorrente-4-5', name: 'Posto Planeta' },
        { id: 'concorrente-4-6', name: 'Posto Galáxia' },
        { id: 'concorrente-4-7', name: 'Posto Nebulosa' },
        { id: 'concorrente-4-8', name: 'Posto Universo' },
        { id: 'concorrente-4-9', name: 'Posto Cosmos' },
        { id: 'concorrente-4-10', name: 'Posto Vácuo' },
    ],
  },
  {
    id: 'posto-natureza-5',
    name: 'Posto Natureza 5',
    competitors: [
        { id: 'concorrente-5-1', name: 'Shell' },
        { id: 'concorrente-5-2', name: 'Ipiranga' },
        { id: 'concorrente-5-3', name: 'Petrobras' },
        { id: 'concorrente-5-4', name: 'ALE' },
        { id: 'concorrente-5-5', name: 'Raízen' },
        { id: 'concorrente-5-6', name: 'Vibra' },
        { id: 'concorrente-5-7', name: 'Total' },
        { id: 'concorrente-5-8', name: 'Setta' },
        { id: 'concorrente-5-9', name: 'Charrua' },
        { id: 'concorrente-5-10', name: 'Outro Posto' },
    ],
  },
];
